import '../styles/globals.css';
// import '../styles/main.scss';
import NavBar from './NavBar';
export const metadata = {
  title: 'FilmFlow',
  description: 'Generated by Next.js',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <NavBar />
        {children}
      </body>
    </html>
  );
}
